module.exports = {
  content: [
    "./src/app/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        'app-yellow': '#E8C967',
        'app-gray-bg': '#F8F8F8',
        'app-text-dark': '#2D2D2D',
        
        // Mustard & Marble Color System
        surface: '#faf9f9',
        'surface-dim': '#dbdad9',
        'surface-bright': '#faf9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container': '#efeded',
        'surface-container-high': '#e9e8e8',
        'surface-container-highest': '#e3e2e2',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#4d4637',
        'inverse-surface': '#2f3031',
        'inverse-on-surface': '#f2f0f0',
        outline: '#7f7665',
        'outline-variant': '#d0c5b1',
        'surface-tint': '#755b00',
        primary: '#755b00',
        'on-primary': '#ffffff',
        'primary-container': '#e6c15d', // Mustard Yellow
        'on-primary-container': '#654e00',
        'inverse-primary': '#e8c25e',
        secondary: '#5f5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-secondary-container': '#636262',
        tertiary: '#5d5f5d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c5c5c2',
        'on-tertiary-container': '#505250',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdf91',
        'primary-fixed-dim': '#e8c25e',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#584400',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#e2e3e0',
        'tertiary-fixed-dim': '#c6c7c4',
        'on-tertiary-fixed': '#1a1c1a',
        'on-tertiary-fixed-variant': '#454745',
        background: '#faf9f9',
        'on-background': '#1b1c1c',
        'surface-variant': '#e3e2e2',
      },
    },
  },
  plugins: [],
}
